### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by tsapa44** [auxilincom/auxilin-merge#2]
```
services:
  auxilin:
    version: 0.2.0
  api:
    version: 0.2.3
    include: true
  web:
    version: 0.2.2
    include: true
  landing:
    version: 0.2.2
    include: true
  drone:
    version: 1.3.1
    include: false
  monitoring:
    version: 0.2.2
    include: false
```
### next-landing-starter ###
```
=== START REMOVE UNNECESSARY FILES FROM HISTORY ===
sed: 1: "package.json": extra characters at the end of p command
sed: illegal option -- z
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```
```
=== END COMMIT FILES ===
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
fatal: tag '0.2.0' already exists
```
